use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A single conversational turn — stored inside `PersistedThread.messages`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    pub id: Uuid,
    pub role: MessageRole,
    pub content: String,
    /// Citations surfaced inline by an assistant message (empty for user messages).
    pub citations: Vec<Citation>,
    /// Suggested follow-up queries generated by the model (usually only on the last turn).
    pub follow_ups: Vec<String>,
    /// Query mode used for this turn.
    pub mode: QueryMode,
    /// Which provider + model generated this response (None for user messages).
    pub model_used: Option<ModelUsed>,
    /// False while the response is still streaming; true once complete.
    pub is_complete: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Message {
    pub fn new_user(content: String, mode: QueryMode) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            role: MessageRole::User,
            content,
            citations: Vec::new(),
            follow_ups: Vec::new(),
            mode,
            model_used: None,
            is_complete: true,
            created_at: now,
            updated_at: now,
        }
    }

    pub fn new_assistant(mode: QueryMode, model_used: ModelUsed) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            role: MessageRole::Assistant,
            content: String::new(),
            citations: Vec::new(),
            follow_ups: Vec::new(),
            mode,
            model_used: Some(model_used),
            is_complete: false,
            created_at: now,
            updated_at: now,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    User,
    Assistant,
    System,
}

/// A cited web or document source attached to an assistant message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Citation {
    pub id: Uuid,
    /// 1-based citation index as rendered in the UI (e.g. [1], [2]).
    pub index: u32,
    pub title: String,
    pub url: String,
    pub favicon_url: Option<String>,
    pub excerpt: Option<String>,
    pub domain: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum QueryMode {
    Ask,
    Research,
    DeepResearch,
    Rag,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelUsed {
    pub provider_id: String,
    pub model_id: String,
    pub tokens_in: Option<u32>,
    pub tokens_out: Option<u32>,
    pub latency_ms: Option<u32>,
}

/// The intermediate research steps taken before the final synthesis.
/// Stored transparently inside the thread for inspection/debug.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResearchTrail {
    pub message_id: Uuid,
    pub rewritten_queries: Vec<String>,
    pub search_results: Vec<SearchResult>,
    pub selected_chunk_count: u32,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SearchResult {
    pub url: String,
    pub title: String,
    pub snippet: String,
    pub rank: u32,
    pub was_fetched: bool,
    pub fetch_status: Option<u16>,
}
